### ISSUE TITLE
Undefined method 'force_encoding' for string when running on ruby 1.8.7

### ISSUE THREAD

**Issue by alishutc** [inossidabile/wash_out#1]
I get this error when trying to call a service when using ruby 1.8.7 - this occurs on line 13 of router.rb.
Is it intended for wash_out to be compatible with 1.8.7, or should I only expect it to work on 1.9?
